branch-defaults:
  default:
    environment: development
    group_suffix: null
  master:
    environment: hellorails-staging-web
    group_suffix: null
global:
  application_name: hellorails
  branch: null
  default_ec2_keyname: AWS-EU-Servers
  default_platform: Ruby 2.3 (Puma)
  default_region: eu-west-1
  profile: null
  repository: null
  sc: null
